<template>
  <AppLayout>
    <TablePageLayout>
      <template #filters>
        <div class="card p-4 sm:p-6 space-y-4">
          <p class="text-sm text-amber-700 dark:text-amber-300">{{ t('admin.userRequestAudit.sensitivity') }}</p>
          <div class="flex flex-wrap items-end gap-4">
            <div v-for="field in filterFields" :key="field" class="w-full sm:w-auto sm:min-w-[170px]"><label class="input-label">{{ t(`admin.userRequestAudit.filters.${field}`) }}</label><input v-model.trim="filters[field]" class="input" @keyup.enter="search" /></div>
            <div><label class="input-label">{{ t('admin.userRequestAudit.filters.protocol') }}</label><Select v-model="filters.protocol" :options="protocolOptions" /></div>
            <div><label class="input-label">{{ t('admin.userRequestAudit.filters.status') }}</label><input v-model.trim="filters.status" class="input" /></div>
            <button class="btn btn-primary" :disabled="loading" @click="search">{{ t('common.search') }}</button><button class="btn btn-secondary" :disabled="loading" @click="resetFilters">{{ t('common.reset') }}</button>
          </div>
          <div class="flex flex-wrap items-end gap-4 border-t pt-4"><div><label class="input-label">{{ t('admin.userRequestAudit.retention') }}</label><input v-model.number="retention" type="number" min="1" max="365" class="input w-32" /></div><button class="btn btn-secondary" :disabled="configSaving" @click="saveConfig">{{ t('common.save') }}</button><span class="text-xs text-gray-500">{{ t('admin.userRequestAudit.retentionNote') }}</span></div>
        </div>
      </template>
      <template #table><DataTable :columns="columns" :data="items" :loading="loading" row-key="id"><template #cell-created_at="{ value }"><span class="whitespace-nowrap">{{ formatTime(value) }}</span></template><template #cell-request="{ row }"><div class="max-w-xs truncate font-mono text-xs">{{ row.protocol }} · {{ row.endpoint }}<br>{{ row.requested_model || '—' }}</div></template><template #cell-status="{ value }"><span class="font-medium">{{ value }}</span></template><template #cell-actions="{ row }"><button class="text-primary-600" @click="openDetail(row.id)">{{ t('admin.userRequestAudit.detail') }}</button></template><template #empty><div class="py-8 text-center text-sm text-gray-500">{{ t('admin.userRequestAudit.empty') }}</div></template></DataTable></template>
      <template #pagination><Pagination v-if="total" :total="total" :page="page" :page-size="pageSize" @update:page="onPageChange" @update:pageSize="onPageSizeChange" /></template>
    </TablePageLayout>
    <BaseDialog :show="detailVisible" :title="t('admin.userRequestAudit.detail')" width="wide" @close="detailVisible=false"><div v-if="detailLoading" class="py-12 text-center">{{ t('common.loading') }}</div><div v-else-if="detail" class="space-y-4 py-2"><div class="grid grid-cols-1 gap-2 text-sm sm:grid-cols-2"><div v-for="key in detailKeys" :key="key"><span class="text-gray-500">{{ key }}:</span> <span class="font-mono break-all">{{ detail[key] ?? '—' }}</span></div></div><div v-if="detail.request_chatml || detail.response_chatml || detail.chatml" class="space-y-3"><div v-if="detail.request_chatml"><h4 class="font-medium">{{ t('admin.userRequestAudit.requestChatml') }}</h4><pre class="max-h-64 overflow-auto whitespace-pre-wrap rounded bg-gray-100 p-3 text-xs dark:bg-dark-800">{{ detail.request_chatml }}</pre></div><div v-if="detail.response_chatml"><h4 class="font-medium">{{ t('admin.userRequestAudit.responseChatml') }}</h4><pre class="max-h-64 overflow-auto whitespace-pre-wrap rounded bg-gray-100 p-3 text-xs dark:bg-dark-800">{{ detail.response_chatml }}</pre></div><div v-if="detail.chatml"><h4 class="font-medium">{{ t('admin.userRequestAudit.mergedChatml') }}</h4><pre class="max-h-96 overflow-auto whitespace-pre-wrap rounded bg-gray-100 p-3 text-xs dark:bg-dark-800">{{ detail.chatml }}</pre></div></div></div></BaseDialog>
  </AppLayout>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { adminAPI, type UserRequestAudit } from '@/api/admin'
import AppLayout from '@/components/layout/AppLayout.vue'; import TablePageLayout from '@/components/layout/TablePageLayout.vue'; import DataTable from '@/components/common/DataTable.vue'; import Pagination from '@/components/common/Pagination.vue'; import Select from '@/components/common/Select.vue'; import BaseDialog from '@/components/common/BaseDialog.vue'; import type { Column } from '@/components/common/types'; import { useAppStore } from '@/stores'
const { t } = useI18n(); const appStore = useAppStore(); const loading=ref(false); const items=ref<UserRequestAudit[]>([]); const total=ref(0); const page=ref(1); const pageSize=ref(20); const retention=ref(7); const configSaving=ref(false); const detailVisible=ref(false); const detailLoading=ref(false); const detail=ref<UserRequestAudit|null>(null); let detailRequest=0
const filters=reactive<Record<string,string>>({user_id:'',group_id:'',requested_model:'',response_id:'',client_request_id:'',status:'',protocol:'',start_time:'',end_time:''}); const filterFields=['user_id','group_id','requested_model','response_id','client_request_id','start_time','end_time']; const protocolOptions=[{value:'',label:'—'},{value:'anthropic_messages',label:'Anthropic'},{value:'openai_responses',label:'OpenAI Responses'},{value:'openai_chat_completions',label:'OpenAI Chat'},{value:'openai_responses_ws',label:'Responses WS'}]; const columns: Column[]=[{key:'created_at',label:'Created'},{key:'request',label:'Request'},{key:'status',label:'Status'},{key:'actions',label:''}]; const detailKeys=['id','created_at','updated_at','expires_at','user_id','api_key_id','group_id','group_name','protocol','endpoint','requested_model','upstream_model','client_request_id','response_id','previous_response_id','fallback_hash','status','input_usage','output_usage','cache_usage','conversation_key','last_error'] as const
function formatTime(value:string){ return value ? new Date(value).toLocaleString() : '—' }
async function fetchItems(){ loading.value=true; try { const res=await adminAPI.userRequestAudit.list({page:page.value,page_size:pageSize.value,...filters}); items.value=res.items; total.value=res.total } catch(e:any){ appStore.showError(e?.message||t('admin.userRequestAudit.loadFailed')) } finally { loading.value=false } }
function search(){page.value=1; fetchItems()} function resetFilters(){Object.keys(filters).forEach(k=>filters[k]=''); search()} function onPageChange(v:number){page.value=v;fetchItems()} function onPageSizeChange(v:number){pageSize.value=v;page.value=1;fetchItems()}
async function openDetail(id:number){const token=++detailRequest; detailVisible.value=true; detailLoading.value=true; detail.value=null; try {const value=await adminAPI.userRequestAudit.get(id); if(token===detailRequest) detail.value=value} catch(e:any){if(token===detailRequest){detailVisible.value=false;appStore.showError(e?.message||t('admin.userRequestAudit.loadFailed'))}} finally {if(token===detailRequest) detailLoading.value=false}}
async function saveConfig(){if(retention.value<1||retention.value>365){appStore.showError(t('admin.userRequestAudit.retentionInvalid'));return} configSaving.value=true;try{const c=await adminAPI.userRequestAudit.updateConfig({retention_days:retention.value});retention.value=c.retention_days}catch(e:any){appStore.showError(e?.message||t('admin.userRequestAudit.configFailed'))}finally{configSaving.value=false}}
onMounted(async()=>{fetchItems();try{retention.value=(await adminAPI.userRequestAudit.getConfig()).retention_days}catch{ /* unavailable config should not hide records */ }})
</script>
